[config]
name = "Me"
sign = "Snake"
level = "debug"

[p2p]
bootnodes = ["2a000000|0236e206fe7c30eedc4626937fe402aa6be4c12d7d6784dc58fca1aa5578696efa@127.0.0.1:4242",
             "fdsfds"]

[weather]
temperature = "cold"

[ethereum]
endpoint = "http://localhost:8545"
nodeStart = "/home/agdean/Projects/MadNet/scripts/start-geth.sh"
keystore = "/home/agdean/Projects/MadNet/assets/test/keys"
timeout = "5s"

[general]
logging = "ethereum.level=info"
name = "General Me"
age = 200
iq = 3.14
